'is_xbuiltin'(0,'/'(('-'),2)).
'is_xbuiltin'(1,'/'(('abs'),2)).
'is_xbuiltin'(2,'/'(('ncompare'),3)).
'is_xbuiltin'(3,'/'(('+'),3)).
'is_xbuiltin'(3,'/'(('ensure_number'),2)).
'is_xbuiltin'(4,'/'(('-'),3)).
'is_xbuiltin'(5,'/'(('*'),3)).
'is_xbuiltin'(6,'/'(('pow'),3)).
'is_xbuiltin'(7,'/'(('min'),3)).
'is_xbuiltin'(8,'/'(('max'),3)).
'is_xbuiltin'(9,'/'(('/'),3)).
'is_xbuiltin'(10,'/'(('bitcount'),2)).
'is_xbuiltin'(10,'/'(('get_lowest_set_bit'),2)).
'is_xbuiltin'(11,'/'(('<<'),3)).
'is_xbuiltin'(12,'/'(('>>'),3)).
'is_xbuiltin'(13,'/'(('getbit'),3)).
'is_xbuiltin'(14,'/'(('setbit'),4)).
'is_xbuiltin'(15,'/'(('flipbit'),3)).
'is_xbuiltin'(16,'/'(('ite'),4)).
'is_xbuiltin'(17,'/'(('\\'),2)).
'is_xbuiltin'(18,'/'(('/\\'),3)).
'is_xbuiltin'(19,'/'(('\\/'),3)).
'is_xbuiltin'(20,'/'(('xor'),3)).
'is_xbuiltin'(21,'/'(('eq'),3)).
'is_xbuiltin'(22,'/'(('impl'),3)).
'is_xbuiltin'(23,'/'(('less'),3)).
'is_xbuiltin'(24,'/'(('div'),3)).
'is_xbuiltin'(25,'/'(('mod'),3)).
'is_xbuiltin'(26,'/'(('gcd'),3)).
'is_xbuiltin'(27,'/'(('modinv'),3)).
'is_xbuiltin'(28,'/'(('gc'),0)).
'is_xbuiltin'(28,'/'(('symgc'),0)).
'is_xbuiltin'(28,'/'(('symgc_off'),0)).
'is_xbuiltin'(28,'/'(('symgc_on'),0)).
'is_xbuiltin'(29,'/'(('to_codes'),2)).
'is_xbuiltin'(31,'/'(('to_ncodes'),2)).
'is_xbuiltin'(33,'/'(('halt'),1)).
'is_xbuiltin'(34,'/'(('new_interactor'),3)).
'is_xbuiltin'(35,'/'(('ask_interactor'),2)).
'is_xbuiltin'(36,'/'(('tell_interactor'),3)).
'is_xbuiltin'(37,'/'(('stop_interactor'),2)).
'is_xbuiltin'(38,'/'(('cputime'),1)).
'is_xbuiltin'(38,'/'(('db_size'),1)).
'is_xbuiltin'(38,'/'(('engines'),1)).
'is_xbuiltin'(38,'/'(('flags'),1)).
'is_xbuiltin'(38,'/'(('heapsizes'),1)).
'is_xbuiltin'(38,'/'(('max_cores'),1)).
'is_xbuiltin'(38,'/'(('max_memory'),1)).
'is_xbuiltin'(38,'/'(('stacksizes'),1)).
'is_xbuiltin'(38,'/'(('symbols'),1)).
'is_xbuiltin'(38,'/'(('thread_count'),1)).
'is_xbuiltin'(38,'/'(('trailsizes'),1)).
'is_xbuiltin'(38,'/'(('used_memory'),1)).
'is_xbuiltin'(38,'/'(('xprofile'),2)).
'is_xbuiltin'(39,'/'(('jcall'),3)).
'is_xbuiltin'(40,'/'(('gvar_set'),2)).
'is_xbuiltin'(41,'/'(('gvar_get'),2)).
'is_xbuiltin'(42,'/'(('gvar_remove'),1)).
'is_xbuiltin'(43,'/'(('random'),2)).
'is_xbuiltin'(44,'/'(('set_random_seed'),1)).
'is_xbuiltin'(45,'/'(('set_format_precision'),1)).
'is_xbuiltin'(45,'/'(('set_precision'),1)).
'is_xbuiltin'(47,'/'(('truncate'),2)).
'is_xbuiltin'(48,'/'(('log'),2)).
'is_xbuiltin'(49,'/'(('sin'),2)).
'is_xbuiltin'(50,'/'(('cos'),2)).
'is_xbuiltin'(51,'/'(('tan'),2)).
'is_xbuiltin'(52,'/'(('asin'),2)).
'is_xbuiltin'(53,'/'(('acos'),2)).
'is_xbuiltin'(54,'/'(('atan'),2)).
'is_xbuiltin'(55,'/'(('arith_const'),2)).
'is_xbuiltin'(56,'/'(('exp'),2)).
'is_xbuiltin'(58,'/'(('new_ops'),2)).
'is_xbuiltin'(59,'/'(('get_pri'),4)).
'is_xbuiltin'(60,'/'(('get_pris'),3)).
'is_xbuiltin'(63,'/'(('all_ops'),2)).
'is_xbuiltin'(64,'/'(('op'),4)).
'is_xbuiltin'(65,'/'(('to_number'),2)).
'is_xbuiltin'(73,'/'(('s_server'),4)).
'is_xbuiltin'(74,'/'(('s_connection'),3)).
'is_xbuiltin'(74,'/'(('s_ping'),2)).
'is_xbuiltin'(75,'/'(('ask_s_server'),1)).
'is_xbuiltin'(76,'/'(('s_disconnect'),1)).
'is_xbuiltin'(81,'/'(('i_server'),4)).
'is_xbuiltin'(82,'/'(('i_connection'),2)).
'is_xbuiltin'(83,'/'(('ask_i_server'),1)).
'is_xbuiltin'(84,'/'(('i_disconnect'),1)).
'is_xbuiltin'(86,'/'(('from_bundle'),2)).
'is_xbuiltin'(88,'/'(('newer_file_of'),3)).
'is_xbuiltin'(89,'/'(('absolute_file_name'),2)).
'is_xbuiltin'(90,'/'(('save_prolog'),1)).
'is_xbuiltin'(91,'/'(('load_prolog'),2)).
'is_xbuiltin'(94,'/'(('file_op'),2)).
'is_xbuiltin'(94,'/'(('file_op'),3)).
'is_xbuiltin'(95,'/'(('system'),1)).
'is_xbuiltin'(96,'/'(('new_java_class'),2)).
'is_xbuiltin'(97,'/'(('new_java_object'),3)).
'is_xbuiltin'(98,'/'(('invoke_java_method'),5)).
'is_xbuiltin'(99,'/'(('get_java_field_handle'),3)).
'is_xbuiltin'(100,'/'(('hub'),1)).
'is_xbuiltin'(101,'/'(('new_logic_thread'),5)).
'is_xbuiltin'(102,'/'(('compare0'),3)).
'is_xbuiltin'(103,'/'(('get_cmd_line_strings'),2)).
'is_xbuiltin'(104,'/'(('add_cmd_arg'),1)).
'is_xbuiltin'(104,'/'(('pop_cmd_arg'),1)).
'is_xbuiltin'(104,'/'(('push_cmd_arg'),1)).
'is_xbuiltin'(105,'/'(('current_system_symbol'),1)).
'is_xbuiltin'(105,'/'(('current_user_symbol'),1)).
'is_xbuiltin'(106,'/'(('add_to_path'),1)).
'is_xbuiltin'(106,'/'(('get_first_on_path'),1)).
'is_xbuiltin'(106,'/'(('pop_from_path'),1)).
'is_xbuiltin'(106,'/'(('push_to_path'),1)).
'is_xbuiltin'(107,'/'(('path_elements'),1)).
'is_xbuiltin'(108,'/'(('clear_path'),0)).
'is_xbuiltin'(109,'/'(('gvar'),1)).
'is_xbuiltin'(110,'/'(('sleep_ns'),1)).
'is_xbuiltin'(111,'/'(('atomic_list_concat'),2)).
'is_xbuiltin'(112,'/'(('open_list'),1)).
'is_xbuiltin'(113,'/'(('list_add'),2)).
'is_xbuiltin'(114,'/'(('close_list'),2)).
'is_xbuiltin'(115,'/'(('java_profiling'),1)).
'is_xbuiltin'(116,'/'(('symtest'),1)).
'is_xbuiltin'(117,'/'(('thread_id'),1)).
'is_xbuiltin'(118,'/'(('to_upper_case'),2)).
'is_xbuiltin'(119,'/'(('to_lower_case'),2)).
'is_xbuiltin'(120,'/'(('concatenate_files'),2)).
'is_xbuiltin'(121,'/'(('subst_atom'),4)).
'is_xbuiltin'(122,'/'(('to_rstring'),2)).
'is_xbuiltin'(123,'/'(('object_to_quoted_string'),2)).
'is_xbuiltin'(125,'/'(('getenv'),2)).
'is_xbuiltin'(127,'/'(('get_working_directory'),1)).
'is_xbuiltin'(128,'/'(('set_working_directory'),2)).
'is_xbuiltin'(130,'/'(('engine_type'),1)).
'is_xbuiltin'(131,'/'(('engine_gc'),0)).
'is_xbuiltin'(132,'/'(('to_set'),2)).
'is_xbuiltin'(133,'/'(('from_set'),2)).
'is_xbuiltin'(134,'/'(('varnumbers'),2)).
'is_xbuiltin'(135,'/'(('ingest_file'),2)).
'is_xbuiltin'(136,'/'(('named_call'),2)).
