; woodworking 'sawing' task with 10 parts
; Machines:
;   1 highspeed-saw
;   1 saw
; random seed: 805811

(define (problem wood-prob)
  (:domain woodworking)
  (:objects
    highspeed-saw0 - highspeed-saw
    saw0 - saw
    blue green white red mauve black - acolour
    beech pine mahogany - awood
    p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 - part
    b0 b1 b2 b3 - board
  )
  (:init
    (= (total-cost) 0)
    (empty highspeed-saw0)
    (unused p0)
    (= (goal-size p0) 5)
    (= (glaze-cost p0) 10)
    (= (grind-cost p0) 15)
    (= (plane-cost p0) 10)
    (unused p1)
    (= (goal-size p1) 9)
    (= (glaze-cost p1) 14)
    (= (grind-cost p1) 27)
    (= (plane-cost p1) 18)
    (unused p2)
    (= (goal-size p2) 9)
    (= (glaze-cost p2) 14)
    (= (grind-cost p2) 27)
    (= (plane-cost p2) 18)
    (unused p3)
    (= (goal-size p3) 13)
    (= (glaze-cost p3) 18)
    (= (grind-cost p3) 39)
    (= (plane-cost p3) 26)
    (unused p4)
    (= (goal-size p4) 10)
    (= (glaze-cost p4) 15)
    (= (grind-cost p4) 30)
    (= (plane-cost p4) 20)
    (unused p5)
    (= (goal-size p5) 6)
    (= (glaze-cost p5) 11)
    (= (grind-cost p5) 18)
    (= (plane-cost p5) 12)
    (unused p6)
    (= (goal-size p6) 5)
    (= (glaze-cost p6) 10)
    (= (grind-cost p6) 15)
    (= (plane-cost p6) 10)
    (unused p7)
    (= (goal-size p7) 12)
    (= (glaze-cost p7) 17)
    (= (grind-cost p7) 36)
    (= (plane-cost p7) 24)
    (unused p8)
    (= (goal-size p8) 10)
    (= (glaze-cost p8) 15)
    (= (grind-cost p8) 30)
    (= (plane-cost p8) 20)
    (unused p9)
    (= (goal-size p9) 10)
    (= (glaze-cost p9) 15)
    (= (grind-cost p9) 30)
    (= (plane-cost p9) 20)
    (= (board-size b0) 33)
    (wood b0 beech)
    (surface-condition b0 rough)
    (available b0)
    (= (board-size b1) 18)
    (wood b1 beech)
    (surface-condition b1 rough)
    (available b1)
    (= (board-size b2) 17)
    (wood b2 mahogany)
    (surface-condition b2 rough)
    (available b2)
    (= (board-size b3) 14)
    (wood b3 pine)
    (surface-condition b3 rough)
    (available b3)
  )
  (:goal
    (and
      (preference g_p0_0 (and
          (wood p0 beech)
          (available p0)
      ))
      (preference g_p1_0 (available p1))
      (preference g_p2_0 (available p2))
      (preference g_p3_0 (and
          (wood p3 beech)
          (available p3)
      ))
      (preference g_p4_0 (available p4))
      (preference g_p5_0 (and
          (wood p5 mahogany)
          (available p5)
      ))
      (preference g_p6_0 (and
          (wood p6 pine)
          (available p6)
      ))
      (preference g_p7_0 (available p7))
      (preference g_p8_0 (available p8))
      (preference g_p9_0 (available p9))
    )
  )
  (:metric maximize
    (- 340
      (+ (total-cost)
         (* (is-violated g_p0_0) 32)
         (* (is-violated g_p1_0) 31)
         (* (is-violated g_p2_0) 26)
         (* (is-violated g_p3_0) 42)
         (* (is-violated g_p4_0) 25)
         (* (is-violated g_p5_0) 35)
         (* (is-violated g_p6_0) 37)
         (* (is-violated g_p7_0) 39)
         (* (is-violated g_p8_0) 34)
         (* (is-violated g_p9_0) 39)
  )))
)
