; woodworking 'sawing' task with 11 parts
; Machines:
;   1 highspeed-saw
;   1 saw
; random seed: 11368

(define (problem wood-prob)
  (:domain woodworking)
  (:objects
    highspeed-saw0 - highspeed-saw
    saw0 - saw
    red green white blue mauve black - acolour
    teak walnut mahogany - awood
    p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 - part
    b0 b1 b2 - board
  )
  (:init
    (= (total-cost) 0)
    (empty highspeed-saw0)
    (unused p0)
    (= (goal-size p0) 8)
    (= (glaze-cost p0) 13)
    (= (grind-cost p0) 24)
    (= (plane-cost p0) 16)
    (unused p1)
    (= (goal-size p1) 8)
    (= (glaze-cost p1) 13)
    (= (grind-cost p1) 24)
    (= (plane-cost p1) 16)
    (unused p2)
    (= (goal-size p2) 12)
    (= (glaze-cost p2) 17)
    (= (grind-cost p2) 36)
    (= (plane-cost p2) 24)
    (unused p3)
    (= (goal-size p3) 12)
    (= (glaze-cost p3) 17)
    (= (grind-cost p3) 36)
    (= (plane-cost p3) 24)
    (unused p4)
    (= (goal-size p4) 13)
    (= (glaze-cost p4) 18)
    (= (grind-cost p4) 39)
    (= (plane-cost p4) 26)
    (unused p5)
    (= (goal-size p5) 15)
    (= (glaze-cost p5) 20)
    (= (grind-cost p5) 45)
    (= (plane-cost p5) 30)
    (unused p6)
    (= (goal-size p6) 13)
    (= (glaze-cost p6) 18)
    (= (grind-cost p6) 39)
    (= (plane-cost p6) 26)
    (unused p7)
    (= (goal-size p7) 5)
    (= (glaze-cost p7) 10)
    (= (grind-cost p7) 15)
    (= (plane-cost p7) 10)
    (unused p8)
    (= (goal-size p8) 13)
    (= (glaze-cost p8) 18)
    (= (grind-cost p8) 39)
    (= (plane-cost p8) 26)
    (unused p9)
    (= (goal-size p9) 9)
    (= (glaze-cost p9) 14)
    (= (grind-cost p9) 27)
    (= (plane-cost p9) 18)
    (unused p10)
    (= (goal-size p10) 11)
    (= (glaze-cost p10) 16)
    (= (grind-cost p10) 33)
    (= (plane-cost p10) 22)
    (= (board-size b0) 45)
    (wood b0 mahogany)
    (surface-condition b0 rough)
    (available b0)
    (= (board-size b1) 39)
    (wood b1 walnut)
    (surface-condition b1 smooth)
    (available b1)
    (= (board-size b2) 25)
    (wood b2 walnut)
    (surface-condition b2 smooth)
    (available b2)
  )
  (:goal
    (and
      (preference g_p0_0 (and
          (wood p0 walnut)
          (available p0)
      ))
      (preference g_p1_0 (and
          (wood p1 walnut)
          (available p1)
      ))
      (preference g_p2_0 (and
          (wood p2 walnut)
          (available p2)
      ))
      (preference g_p3_0 (and
          (wood p3 mahogany)
          (available p3)
      ))
      (preference g_p4_0 (and
          (wood p4 mahogany)
          (available p4)
      ))
      (preference g_p5_0 (and
          (wood p5 walnut)
          (available p5)
      ))
      (preference g_p6_0 (available p6))
      (preference g_p7_0 (and
          (wood p7 walnut)
          (available p7)
      ))
      (preference g_p8_0 (and
          (wood p8 mahogany)
          (available p8)
      ))
      (preference g_p9_0 (available p9))
      (preference g_p10_0 (available p10))
    )
  )
  (:metric maximize
    (- 426
      (+ (total-cost)
         (* (is-violated g_p0_0) 49)
         (* (is-violated g_p1_0) 39)
         (* (is-violated g_p2_0) 31)
         (* (is-violated g_p3_0) 45)
         (* (is-violated g_p4_0) 39)
         (* (is-violated g_p5_0) 46)
         (* (is-violated g_p6_0) 33)
         (* (is-violated g_p7_0) 40)
         (* (is-violated g_p8_0) 37)
         (* (is-violated g_p9_0) 30)
         (* (is-violated g_p10_0) 37)
  )))
)
