; woodworking 'choose one' task with 7 parts
; Machines:
;   1 grinder
;   1 glazer
;   1 immersion-varnisher
;   1 planer
;   1 highspeed-saw
;   1 spray-varnisher
;   1 saw
; random seed: 815901

(define (problem wood-prob)
  (:domain woodworking)
  (:objects
    grinder0 - grinder
    glazer0 - glazer
    immersion-varnisher0 - immersion-varnisher
    planer0 - planer
    highspeed-saw0 - highspeed-saw
    spray-varnisher0 - spray-varnisher
    saw0 - saw
    green blue black white mauve - acolour
    teak beech - awood
    p0 p1 p2 p3 p4 p5 p6 - part
    b0 b1 b2 b3 - board
  )
  (:init
    (grind-treatment-change varnished colourfragments)
    (grind-treatment-change glazed untreated)
    (grind-treatment-change untreated untreated)
    (grind-treatment-change colourfragments untreated)
    (is-smooth smooth)
    (is-smooth verysmooth)
    (= (total-cost) 0)
    (has-colour glazer0 blue)
    (has-colour glazer0 black)
    (has-colour glazer0 natural)
    (has-colour glazer0 green)
    (has-colour glazer0 mauve)
    (has-colour immersion-varnisher0 blue)
    (has-colour immersion-varnisher0 green)
    (has-colour immersion-varnisher0 natural)
    (has-colour immersion-varnisher0 mauve)
    (empty highspeed-saw0)
    (has-colour spray-varnisher0 blue)
    (has-colour spray-varnisher0 green)
    (has-colour spray-varnisher0 natural)
    (has-colour spray-varnisher0 mauve)
    (unused p0)
    (= (goal-size p0) 13)
    (= (glaze-cost p0) 18)
    (= (grind-cost p0) 39)
    (= (plane-cost p0) 26)
    (unused p1)
    (= (goal-size p1) 7)
    (= (glaze-cost p1) 12)
    (= (grind-cost p1) 21)
    (= (plane-cost p1) 14)
    (unused p2)
    (= (goal-size p2) 6)
    (= (glaze-cost p2) 11)
    (= (grind-cost p2) 18)
    (= (plane-cost p2) 12)
    (unused p3)
    (= (goal-size p3) 7)
    (= (glaze-cost p3) 12)
    (= (grind-cost p3) 21)
    (= (plane-cost p3) 14)
    (unused p4)
    (= (goal-size p4) 10)
    (= (glaze-cost p4) 15)
    (= (grind-cost p4) 30)
    (= (plane-cost p4) 20)
    (unused p5)
    (= (goal-size p5) 12)
    (= (glaze-cost p5) 17)
    (= (grind-cost p5) 36)
    (= (plane-cost p5) 24)
    (unused p6)
    (= (goal-size p6) 12)
    (= (glaze-cost p6) 17)
    (= (grind-cost p6) 36)
    (= (plane-cost p6) 24)
    (= (board-size b0) 39)
    (wood b0 beech)
    (surface-condition b0 rough)
    (available b0)
    (= (board-size b1) 46)
    (wood b1 beech)
    (surface-condition b1 smooth)
    (available b1)
    (= (board-size b2) 33)
    (wood b2 teak)
    (surface-condition b2 smooth)
    (available b2)
    (= (board-size b3) 35)
    (wood b3 teak)
    (surface-condition b3 rough)
    (available b3)
  )
  (:goal
    (and
      (preference g_p0_0 (and
          (surface-condition p0 smooth)
          (treatment p0 glazed)
          (available p0)
      ))
      (preference g_p0_1 (and
          (wood p0 beech)
          (surface-condition p0 smooth)
          (treatment p0 varnished)
          (available p0)
      ))
      (preference g_p0_2 (and
          (colour p0 natural)
          (wood p0 teak)
          (available p0)
      ))
      (preference g_p0_3 (and
          (colour p0 blue)
          (wood p0 beech)
          (available p0)
      ))
      (preference g_p1_0 (and
          (wood p1 beech)
          (treatment p1 glazed)
          (available p1)
      ))
      (preference g_p1_1 (and
          (surface-condition p1 verysmooth)
          (treatment p1 glazed)
          (available p1)
      ))
      (preference g_p1_2 (and
          (colour p1 green)
          (wood p1 teak)
          (treatment p1 glazed)
          (available p1)
      ))
      (preference g_p1_3 (and
          (wood p1 teak)
          (surface-condition p1 verysmooth)
          (available p1)
      ))
      (preference g_p2_0 (and
          (colour p2 natural)
          (wood p2 teak)
          (surface-condition p2 verysmooth)
          (treatment p2 glazed)
          (available p2)
      ))
      (preference g_p2_1 (and
          (colour p2 green)
          (wood p2 teak)
          (available p2)
      ))
      (preference g_p2_2 (and
          (colour p2 blue)
          (wood p2 beech)
          (surface-condition p2 verysmooth)
          (treatment p2 glazed)
          (available p2)
      ))
      (preference g_p3_0 (and
          (colour p3 natural)
          (surface-condition p3 smooth)
          (treatment p3 varnished)
          (available p3)
      ))
      (preference g_p3_1 (and
          (colour p3 green)
          (surface-condition p3 smooth)
          (treatment p3 glazed)
          (available p3)
      ))
      (preference g_p4_0 (and
          (colour p4 blue)
          (treatment p4 varnished)
          (available p4)
      ))
      (preference g_p4_1 (and
          (colour p4 mauve)
          (wood p4 teak)
          (surface-condition p4 verysmooth)
          (available p4)
      ))
      (preference g_p4_2 (and
          (colour p4 mauve)
          (treatment p4 glazed)
          (available p4)
      ))
      (preference g_p4_3 (and
          (wood p4 beech)
          (treatment p4 varnished)
          (available p4)
      ))
      (preference g_p5_0 (and
          (colour p5 blue)
          (surface-condition p5 verysmooth)
          (treatment p5 glazed)
          (available p5)
      ))
      (preference g_p5_1 (and
          (colour p5 blue)
          (wood p5 beech)
          (surface-condition p5 verysmooth)
          (treatment p5 varnished)
          (available p5)
      ))
      (preference g_p5_2 (and
          (colour p5 natural)
          (wood p5 beech)
          (surface-condition p5 verysmooth)
          (treatment p5 glazed)
          (available p5)
      ))
      (preference g_p6_0 (and
          (colour p6 black)
          (wood p6 teak)
          (surface-condition p6 smooth)
          (treatment p6 glazed)
          (available p6)
      ))
      (preference g_p6_1 (and
          (colour p6 blue)
          (wood p6 beech)
          (surface-condition p6 verysmooth)
          (treatment p6 glazed)
          (available p6)
      ))
    )
  )
  (:metric maximize
    (- 1723
      (+ (total-cost)
         (* (is-violated g_p0_0) 113)
         (* (is-violated g_p0_1) 105)
         (* (is-violated g_p0_2) 59)
         (* (is-violated g_p0_3) 65)
         (* (is-violated g_p1_0) 47)
         (* (is-violated g_p1_1) 72)
         (* (is-violated g_p1_2) 51)
         (* (is-violated g_p1_3) 69)
         (* (is-violated g_p2_0) 84)
         (* (is-violated g_p2_1) 62)
         (* (is-violated g_p2_2) 69)
         (* (is-violated g_p3_0) 81)
         (* (is-violated g_p3_1) 81)
         (* (is-violated g_p4_0) 47)
         (* (is-violated g_p4_1) 98)
         (* (is-violated g_p4_2) 44)
         (* (is-violated g_p4_3) 66)
         (* (is-violated g_p5_0) 87)
         (* (is-violated g_p5_1) 116)
         (* (is-violated g_p5_2) 90)
         (* (is-violated g_p6_0) 104)
         (* (is-violated g_p6_1) 113)
  )))
)
