; woodworking 'choose one' task with 10 parts
; Machines:
;   1 grinder
;   1 glazer
;   1 immersion-varnisher
;   1 planer
;   1 highspeed-saw
;   1 spray-varnisher
;   1 saw
; random seed: 580512

(define (problem wood-prob)
  (:domain woodworking)
  (:objects
    grinder0 - grinder
    glazer0 - glazer
    immersion-varnisher0 - immersion-varnisher
    planer0 - planer
    highspeed-saw0 - highspeed-saw
    spray-varnisher0 - spray-varnisher
    saw0 - saw
    blue green white mauve black red - acolour
    teak pine mahogany - awood
    p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 - part
    b0 b1 b2 b3 b4 b5 - board
  )
  (:init
    (grind-treatment-change varnished colourfragments)
    (grind-treatment-change glazed untreated)
    (grind-treatment-change untreated untreated)
    (grind-treatment-change colourfragments untreated)
    (is-smooth smooth)
    (is-smooth verysmooth)
    (= (total-cost) 0)
    (has-colour glazer0 blue)
    (has-colour glazer0 natural)
    (has-colour glazer0 mauve)
    (has-colour glazer0 green)
    (has-colour glazer0 black)
    (has-colour glazer0 red)
    (has-colour immersion-varnisher0 blue)
    (has-colour immersion-varnisher0 natural)
    (has-colour immersion-varnisher0 mauve)
    (has-colour immersion-varnisher0 black)
    (has-colour immersion-varnisher0 green)
    (has-colour immersion-varnisher0 white)
    (has-colour immersion-varnisher0 red)
    (empty highspeed-saw0)
    (has-colour spray-varnisher0 blue)
    (has-colour spray-varnisher0 natural)
    (has-colour spray-varnisher0 mauve)
    (has-colour spray-varnisher0 black)
    (has-colour spray-varnisher0 green)
    (has-colour spray-varnisher0 white)
    (has-colour spray-varnisher0 red)
    (unused p0)
    (= (goal-size p0) 5)
    (= (glaze-cost p0) 10)
    (= (grind-cost p0) 15)
    (= (plane-cost p0) 10)
    (unused p1)
    (= (goal-size p1) 5)
    (= (glaze-cost p1) 10)
    (= (grind-cost p1) 15)
    (= (plane-cost p1) 10)
    (unused p2)
    (= (goal-size p2) 6)
    (= (glaze-cost p2) 11)
    (= (grind-cost p2) 18)
    (= (plane-cost p2) 12)
    (unused p3)
    (= (goal-size p3) 10)
    (= (glaze-cost p3) 15)
    (= (grind-cost p3) 30)
    (= (plane-cost p3) 20)
    (unused p4)
    (= (goal-size p4) 13)
    (= (glaze-cost p4) 18)
    (= (grind-cost p4) 39)
    (= (plane-cost p4) 26)
    (unused p5)
    (= (goal-size p5) 12)
    (= (glaze-cost p5) 17)
    (= (grind-cost p5) 36)
    (= (plane-cost p5) 24)
    (unused p6)
    (= (goal-size p6) 14)
    (= (glaze-cost p6) 19)
    (= (grind-cost p6) 42)
    (= (plane-cost p6) 28)
    (unused p7)
    (= (goal-size p7) 15)
    (= (glaze-cost p7) 20)
    (= (grind-cost p7) 45)
    (= (plane-cost p7) 30)
    (unused p8)
    (= (goal-size p8) 10)
    (= (glaze-cost p8) 15)
    (= (grind-cost p8) 30)
    (= (plane-cost p8) 20)
    (unused p9)
    (= (goal-size p9) 13)
    (= (glaze-cost p9) 18)
    (= (grind-cost p9) 39)
    (= (plane-cost p9) 26)
    (= (board-size b0) 29)
    (wood b0 teak)
    (surface-condition b0 rough)
    (available b0)
    (= (board-size b1) 38)
    (wood b1 mahogany)
    (surface-condition b1 rough)
    (available b1)
    (= (board-size b2) 51)
    (wood b2 mahogany)
    (surface-condition b2 rough)
    (available b2)
    (= (board-size b3) 13)
    (wood b3 mahogany)
    (surface-condition b3 rough)
    (available b3)
    (= (board-size b4) 36)
    (wood b4 pine)
    (surface-condition b4 rough)
    (available b4)
    (= (board-size b5) 39)
    (wood b5 pine)
    (surface-condition b5 smooth)
    (available b5)
  )
  (:goal
    (and
      (preference g_p0_0 (and
          (colour p0 natural)
          (wood p0 teak)
          (surface-condition p0 verysmooth)
          (available p0)
      ))
      (preference g_p0_1 (and
          (colour p0 green)
          (wood p0 teak)
          (available p0)
      ))
      (preference g_p0_2 (and
          (colour p0 blue)
          (treatment p0 varnished)
          (available p0)
      ))
      (preference g_p0_3 (and
          (wood p0 mahogany)
          (surface-condition p0 verysmooth)
          (available p0)
      ))
      (preference g_p1_0 (and
          (colour p1 red)
          (wood p1 pine)
          (surface-condition p1 smooth)
          (treatment p1 varnished)
          (available p1)
      ))
      (preference g_p1_1 (and
          (colour p1 black)
          (surface-condition p1 verysmooth)
          (treatment p1 varnished)
          (available p1)
      ))
      (preference g_p1_2 (and
          (colour p1 white)
          (wood p1 teak)
          (surface-condition p1 verysmooth)
          (treatment p1 varnished)
          (available p1)
      ))
      (preference g_p1_3 (and
          (surface-condition p1 smooth)
          (treatment p1 glazed)
          (available p1)
      ))
      (preference g_p2_0 (and
          (colour p2 black)
          (treatment p2 varnished)
          (available p2)
      ))
      (preference g_p2_1 (and
          (colour p2 green)
          (wood p2 pine)
          (surface-condition p2 verysmooth)
          (treatment p2 glazed)
          (available p2)
      ))
      (preference g_p3_0 (and
          (colour p3 green)
          (wood p3 mahogany)
          (surface-condition p3 smooth)
          (available p3)
      ))
      (preference g_p3_1 (and
          (colour p3 blue)
          (wood p3 mahogany)
          (surface-condition p3 verysmooth)
          (treatment p3 glazed)
          (available p3)
      ))
      (preference g_p4_0 (and
          (colour p4 natural)
          (treatment p4 varnished)
          (available p4)
      ))
      (preference g_p4_1 (and
          (wood p4 pine)
          (treatment p4 glazed)
          (available p4)
      ))
      (preference g_p4_2 (and
          (colour p4 black)
          (wood p4 mahogany)
          (available p4)
      ))
      (preference g_p5_0 (and
          (colour p5 white)
          (wood p5 pine)
          (surface-condition p5 smooth)
          (treatment p5 varnished)
          (available p5)
      ))
      (preference g_p5_1 (and
          (colour p5 white)
          (surface-condition p5 verysmooth)
          (treatment p5 varnished)
          (available p5)
      ))
      (preference g_p6_0 (and
          (colour p6 green)
          (surface-condition p6 verysmooth)
          (treatment p6 glazed)
          (available p6)
      ))
      (preference g_p6_1 (and
          (wood p6 pine)
          (treatment p6 glazed)
          (available p6)
      ))
      (preference g_p6_2 (and
          (colour p6 green)
          (wood p6 teak)
          (treatment p6 varnished)
          (available p6)
      ))
      (preference g_p6_3 (and
          (colour p6 mauve)
          (treatment p6 glazed)
          (available p6)
      ))
      (preference g_p7_0 (and
          (colour p7 mauve)
          (wood p7 pine)
          (surface-condition p7 verysmooth)
          (available p7)
      ))
      (preference g_p7_1 (and
          (colour p7 natural)
          (wood p7 mahogany)
          (surface-condition p7 smooth)
          (treatment p7 varnished)
          (available p7)
      ))
      (preference g_p8_0 (and
          (surface-condition p8 smooth)
          (treatment p8 varnished)
          (available p8)
      ))
      (preference g_p8_1 (and
          (colour p8 natural)
          (wood p8 mahogany)
          (available p8)
      ))
      (preference g_p8_2 (and
          (colour p8 mauve)
          (wood p8 pine)
          (available p8)
      ))
      (preference g_p8_3 (and
          (colour p8 red)
          (treatment p8 glazed)
          (available p8)
      ))
      (preference g_p9_0 (and
          (colour p9 green)
          (surface-condition p9 verysmooth)
          (treatment p9 varnished)
          (available p9)
      ))
      (preference g_p9_1 (and
          (colour p9 red)
          (wood p9 mahogany)
          (surface-condition p9 verysmooth)
          (treatment p9 glazed)
          (available p9)
      ))
      (preference g_p9_2 (and
          (colour p9 white)
          (wood p9 mahogany)
          (treatment p9 varnished)
          (available p9)
      ))
      (preference g_p9_3 (and
          (colour p9 blue)
          (wood p9 mahogany)
          (surface-condition p9 verysmooth)
          (treatment p9 varnished)
          (available p9)
      ))
    )
  )
  (:metric maximize
    (- 2410
      (+ (total-cost)
         (* (is-violated g_p0_0) 66)
         (* (is-violated g_p0_1) 53)
         (* (is-violated g_p0_2) 41)
         (* (is-violated g_p0_3) 59)
         (* (is-violated g_p1_0) 69)
         (* (is-violated g_p1_1) 56)
         (* (is-violated g_p1_2) 70)
         (* (is-violated g_p1_3) 65)
         (* (is-violated g_p2_0) 39)
         (* (is-violated g_p2_1) 67)
         (* (is-violated g_p3_0) 96)
         (* (is-violated g_p3_1) 110)
         (* (is-violated g_p4_0) 55)
         (* (is-violated g_p4_1) 68)
         (* (is-violated g_p4_2) 64)
         (* (is-violated g_p5_0) 101)
         (* (is-violated g_p5_1) 107)
         (* (is-violated g_p6_0) 117)
         (* (is-violated g_p6_1) 68)
         (* (is-violated g_p6_2) 69)
         (* (is-violated g_p6_3) 56)
         (* (is-violated g_p7_0) 96)
         (* (is-violated g_p7_1) 127)
         (* (is-violated g_p8_0) 100)
         (* (is-violated g_p8_1) 50)
         (* (is-violated g_p8_2) 69)
         (* (is-violated g_p8_3) 51)
         (* (is-violated g_p9_0) 116)
         (* (is-violated g_p9_1) 120)
         (* (is-violated g_p9_2) 69)
         (* (is-violated g_p9_3) 116)
  )))
)
