; woodworking 'choose one' task with 11 parts
; Machines:
;   1 grinder
;   1 glazer
;   1 immersion-varnisher
;   1 planer
;   1 highspeed-saw
;   1 spray-varnisher
;   1 saw
; random seed: 743712

(define (problem wood-prob)
  (:domain woodworking)
  (:objects
    grinder0 - grinder
    glazer0 - glazer
    immersion-varnisher0 - immersion-varnisher
    planer0 - planer
    highspeed-saw0 - highspeed-saw
    spray-varnisher0 - spray-varnisher
    saw0 - saw
    green blue black red white mauve - acolour
    teak beech pine - awood
    p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 - part
    b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 - board
  )
  (:init
    (grind-treatment-change varnished colourfragments)
    (grind-treatment-change glazed untreated)
    (grind-treatment-change untreated untreated)
    (grind-treatment-change colourfragments untreated)
    (is-smooth smooth)
    (is-smooth verysmooth)
    (= (total-cost) 0)
    (has-colour glazer0 blue)
    (has-colour glazer0 natural)
    (has-colour glazer0 mauve)
    (has-colour glazer0 black)
    (has-colour glazer0 green)
    (has-colour glazer0 white)
    (has-colour glazer0 red)
    (has-colour immersion-varnisher0 blue)
    (has-colour immersion-varnisher0 natural)
    (has-colour immersion-varnisher0 mauve)
    (has-colour immersion-varnisher0 green)
    (has-colour immersion-varnisher0 black)
    (has-colour immersion-varnisher0 white)
    (has-colour immersion-varnisher0 red)
    (empty highspeed-saw0)
    (has-colour spray-varnisher0 blue)
    (has-colour spray-varnisher0 natural)
    (has-colour spray-varnisher0 mauve)
    (has-colour spray-varnisher0 green)
    (has-colour spray-varnisher0 black)
    (has-colour spray-varnisher0 white)
    (has-colour spray-varnisher0 red)
    (unused p0)
    (= (goal-size p0) 12)
    (= (glaze-cost p0) 17)
    (= (grind-cost p0) 36)
    (= (plane-cost p0) 24)
    (unused p1)
    (= (goal-size p1) 5)
    (= (glaze-cost p1) 10)
    (= (grind-cost p1) 15)
    (= (plane-cost p1) 10)
    (unused p2)
    (= (goal-size p2) 10)
    (= (glaze-cost p2) 15)
    (= (grind-cost p2) 30)
    (= (plane-cost p2) 20)
    (unused p3)
    (= (goal-size p3) 5)
    (= (glaze-cost p3) 10)
    (= (grind-cost p3) 15)
    (= (plane-cost p3) 10)
    (unused p4)
    (= (goal-size p4) 7)
    (= (glaze-cost p4) 12)
    (= (grind-cost p4) 21)
    (= (plane-cost p4) 14)
    (unused p5)
    (= (goal-size p5) 13)
    (= (glaze-cost p5) 18)
    (= (grind-cost p5) 39)
    (= (plane-cost p5) 26)
    (unused p6)
    (= (goal-size p6) 10)
    (= (glaze-cost p6) 15)
    (= (grind-cost p6) 30)
    (= (plane-cost p6) 20)
    (unused p7)
    (= (goal-size p7) 12)
    (= (glaze-cost p7) 17)
    (= (grind-cost p7) 36)
    (= (plane-cost p7) 24)
    (unused p8)
    (= (goal-size p8) 8)
    (= (glaze-cost p8) 13)
    (= (grind-cost p8) 24)
    (= (plane-cost p8) 16)
    (unused p9)
    (= (goal-size p9) 15)
    (= (glaze-cost p9) 20)
    (= (grind-cost p9) 45)
    (= (plane-cost p9) 30)
    (unused p10)
    (= (goal-size p10) 8)
    (= (glaze-cost p10) 13)
    (= (grind-cost p10) 24)
    (= (plane-cost p10) 16)
    (= (board-size b0) 25)
    (wood b0 beech)
    (surface-condition b0 smooth)
    (available b0)
    (= (board-size b1) 39)
    (wood b1 beech)
    (surface-condition b1 rough)
    (available b1)
    (= (board-size b2) 30)
    (wood b2 beech)
    (surface-condition b2 rough)
    (available b2)
    (= (board-size b3) 34)
    (wood b3 teak)
    (surface-condition b3 rough)
    (available b3)
    (= (board-size b4) 37)
    (wood b4 teak)
    (surface-condition b4 rough)
    (available b4)
    (= (board-size b5) 44)
    (wood b5 teak)
    (surface-condition b5 rough)
    (available b5)
    (= (board-size b6) 23)
    (wood b6 teak)
    (surface-condition b6 rough)
    (available b6)
    (= (board-size b7) 44)
    (wood b7 pine)
    (surface-condition b7 rough)
    (available b7)
    (= (board-size b8) 38)
    (wood b8 pine)
    (surface-condition b8 rough)
    (available b8)
    (= (board-size b9) 8)
    (wood b9 pine)
    (surface-condition b9 rough)
    (available b9)
  )
  (:goal
    (and
      (preference g_p0_0 (and
          (wood p0 pine)
          (treatment p0 glazed)
          (available p0)
      ))
      (preference g_p0_1 (and
          (wood p0 teak)
          (treatment p0 glazed)
          (available p0)
      ))
      (preference g_p0_2 (and
          (colour p0 red)
          (wood p0 pine)
          (surface-condition p0 verysmooth)
          (available p0)
      ))
      (preference g_p0_3 (and
          (colour p0 mauve)
          (wood p0 teak)
          (surface-condition p0 verysmooth)
          (treatment p0 varnished)
          (available p0)
      ))
      (preference g_p1_0 (and
          (colour p1 natural)
          (wood p1 teak)
          (surface-condition p1 smooth)
          (treatment p1 varnished)
          (available p1)
      ))
      (preference g_p1_1 (and
          (colour p1 green)
          (surface-condition p1 smooth)
          (treatment p1 varnished)
          (available p1)
      ))
      (preference g_p1_2 (and
          (colour p1 blue)
          (wood p1 beech)
          (surface-condition p1 verysmooth)
          (treatment p1 glazed)
          (available p1)
      ))
      (preference g_p1_3 (and
          (wood p1 beech)
          (treatment p1 varnished)
          (available p1)
      ))
      (preference g_p2_0 (and
          (colour p2 blue)
          (wood p2 beech)
          (surface-condition p2 verysmooth)
          (treatment p2 glazed)
          (available p2)
      ))
      (preference g_p2_1 (and
          (colour p2 white)
          (wood p2 pine)
          (treatment p2 varnished)
          (available p2)
      ))
      (preference g_p2_2 (and
          (wood p2 pine)
          (surface-condition p2 verysmooth)
          (available p2)
      ))
      (preference g_p3_0 (and
          (colour p3 natural)
          (surface-condition p3 verysmooth)
          (available p3)
      ))
      (preference g_p3_1 (and
          (colour p3 green)
          (wood p3 beech)
          (surface-condition p3 smooth)
          (treatment p3 varnished)
          (available p3)
      ))
      (preference g_p3_2 (and
          (colour p3 red)
          (wood p3 teak)
          (surface-condition p3 verysmooth)
          (treatment p3 glazed)
          (available p3)
      ))
      (preference g_p3_3 (and
          (colour p3 red)
          (wood p3 beech)
          (surface-condition p3 verysmooth)
          (available p3)
      ))
      (preference g_p4_0 (and
          (colour p4 black)
          (wood p4 teak)
          (treatment p4 glazed)
          (available p4)
      ))
      (preference g_p4_1 (and
          (colour p4 green)
          (surface-condition p4 smooth)
          (available p4)
      ))
      (preference g_p4_2 (and
          (colour p4 blue)
          (wood p4 pine)
          (surface-condition p4 smooth)
          (treatment p4 glazed)
          (available p4)
      ))
      (preference g_p4_3 (and
          (wood p4 teak)
          (treatment p4 varnished)
          (available p4)
      ))
      (preference g_p5_0 (and
          (colour p5 green)
          (wood p5 beech)
          (surface-condition p5 smooth)
          (available p5)
      ))
      (preference g_p5_1 (and
          (colour p5 black)
          (wood p5 beech)
          (surface-condition p5 smooth)
          (treatment p5 varnished)
          (available p5)
      ))
      (preference g_p5_2 (and
          (colour p5 red)
          (wood p5 pine)
          (surface-condition p5 verysmooth)
          (treatment p5 varnished)
          (available p5)
      ))
      (preference g_p5_3 (and
          (colour p5 green)
          (wood p5 teak)
          (available p5)
      ))
      (preference g_p6_0 (and
          (wood p6 teak)
          (surface-condition p6 smooth)
          (available p6)
      ))
      (preference g_p6_1 (and
          (colour p6 red)
          (wood p6 teak)
          (surface-condition p6 verysmooth)
          (treatment p6 glazed)
          (available p6)
      ))
      (preference g_p6_2 (and
          (wood p6 teak)
          (treatment p6 varnished)
          (available p6)
      ))
      (preference g_p6_3 (and
          (colour p6 red)
          (wood p6 pine)
          (treatment p6 glazed)
          (available p6)
      ))
      (preference g_p7_0 (and
          (colour p7 mauve)
          (wood p7 teak)
          (available p7)
      ))
      (preference g_p7_1 (and
          (colour p7 blue)
          (surface-condition p7 verysmooth)
          (available p7)
      ))
      (preference g_p7_2 (and
          (wood p7 teak)
          (surface-condition p7 smooth)
          (treatment p7 varnished)
          (available p7)
      ))
      (preference g_p7_3 (and
          (colour p7 mauve)
          (surface-condition p7 smooth)
          (treatment p7 glazed)
          (available p7)
      ))
      (preference g_p8_0 (and
          (colour p8 blue)
          (wood p8 beech)
          (surface-condition p8 smooth)
          (treatment p8 varnished)
          (available p8)
      ))
      (preference g_p8_1 (and
          (colour p8 green)
          (wood p8 pine)
          (surface-condition p8 smooth)
          (treatment p8 varnished)
          (available p8)
      ))
      (preference g_p9_0 (and
          (colour p9 black)
          (wood p9 teak)
          (surface-condition p9 verysmooth)
          (treatment p9 varnished)
          (available p9)
      ))
      (preference g_p9_1 (and
          (wood p9 beech)
          (surface-condition p9 smooth)
          (available p9)
      ))
      (preference g_p9_2 (and
          (colour p9 white)
          (wood p9 beech)
          (surface-condition p9 verysmooth)
          (treatment p9 varnished)
          (available p9)
      ))
      (preference g_p10_0 (and
          (colour p10 black)
          (treatment p10 varnished)
          (available p10)
      ))
      (preference g_p10_1 (and
          (wood p10 pine)
          (surface-condition p10 smooth)
          (treatment p10 glazed)
          (available p10)
      ))
      (preference g_p10_2 (and
          (colour p10 white)
          (wood p10 teak)
          (treatment p10 glazed)
          (available p10)
      ))
    )
  )
  (:metric maximize
    (- 3114
      (+ (total-cost)
         (* (is-violated g_p0_0) 52)
         (* (is-violated g_p0_1) 51)
         (* (is-violated g_p0_2) 99)
         (* (is-violated g_p0_3) 132)
         (* (is-violated g_p1_0) 75)
         (* (is-violated g_p1_1) 72)
         (* (is-violated g_p1_2) 70)
         (* (is-violated g_p1_3) 53)
         (* (is-violated g_p2_0) 89)
         (* (is-violated g_p2_1) 48)
         (* (is-violated g_p2_2) 83)
         (* (is-violated g_p3_0) 59)
         (* (is-violated g_p3_1) 80)
         (* (is-violated g_p3_2) 68)
         (* (is-violated g_p3_3) 68)
         (* (is-violated g_p4_0) 48)
         (* (is-violated g_p4_1) 72)
         (* (is-violated g_p4_2) 82)
         (* (is-violated g_p4_3) 44)
         (* (is-violated g_p5_0) 106)
         (* (is-violated g_p5_1) 125)
         (* (is-violated g_p5_2) 108)
         (* (is-violated g_p5_3) 63)
         (* (is-violated g_p6_0) 87)
         (* (is-violated g_p6_1) 103)
         (* (is-violated g_p6_2) 62)
         (* (is-violated g_p6_3) 61)
         (* (is-violated g_p7_0) 51)
         (* (is-violated g_p7_1) 116)
         (* (is-violated g_p7_2) 123)
         (* (is-violated g_p7_3) 94)
         (* (is-violated g_p8_0) 86)
         (* (is-violated g_p8_1) 84)
         (* (is-violated g_p9_0) 116)
         (* (is-violated g_p9_1) 101)
         (* (is-violated g_p9_2) 106)
         (* (is-violated g_p10_0) 51)
         (* (is-violated g_p10_1) 78)
         (* (is-violated g_p10_2) 48)
  )))
)
