; woodworking 'choose one' task with 12 parts
; Machines:
;   1 grinder
;   1 glazer
;   1 immersion-varnisher
;   1 planer
;   1 highspeed-saw
;   1 spray-varnisher
;   1 saw
; random seed: 490687

(define (problem wood-prob)
  (:domain woodworking)
  (:objects
    grinder0 - grinder
    glazer0 - glazer
    immersion-varnisher0 - immersion-varnisher
    planer0 - planer
    highspeed-saw0 - highspeed-saw
    spray-varnisher0 - spray-varnisher
    saw0 - saw
    black blue red mauve green white - acolour
    pine teak walnut - awood
    p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 - part
    b0 b1 b2 b3 b4 b5 b6 b7 - board
  )
  (:init
    (grind-treatment-change varnished colourfragments)
    (grind-treatment-change glazed untreated)
    (grind-treatment-change untreated untreated)
    (grind-treatment-change colourfragments untreated)
    (is-smooth smooth)
    (is-smooth verysmooth)
    (= (total-cost) 0)
    (has-colour glazer0 blue)
    (has-colour glazer0 natural)
    (has-colour glazer0 mauve)
    (has-colour glazer0 green)
    (has-colour glazer0 black)
    (has-colour glazer0 white)
    (has-colour glazer0 red)
    (has-colour immersion-varnisher0 blue)
    (has-colour immersion-varnisher0 mauve)
    (has-colour immersion-varnisher0 black)
    (has-colour immersion-varnisher0 green)
    (has-colour immersion-varnisher0 white)
    (has-colour immersion-varnisher0 red)
    (empty highspeed-saw0)
    (has-colour spray-varnisher0 blue)
    (has-colour spray-varnisher0 mauve)
    (has-colour spray-varnisher0 black)
    (has-colour spray-varnisher0 green)
    (has-colour spray-varnisher0 white)
    (has-colour spray-varnisher0 red)
    (unused p0)
    (= (goal-size p0) 8)
    (= (glaze-cost p0) 13)
    (= (grind-cost p0) 24)
    (= (plane-cost p0) 16)
    (unused p1)
    (= (goal-size p1) 11)
    (= (glaze-cost p1) 16)
    (= (grind-cost p1) 33)
    (= (plane-cost p1) 22)
    (unused p2)
    (= (goal-size p2) 8)
    (= (glaze-cost p2) 13)
    (= (grind-cost p2) 24)
    (= (plane-cost p2) 16)
    (unused p3)
    (= (goal-size p3) 5)
    (= (glaze-cost p3) 10)
    (= (grind-cost p3) 15)
    (= (plane-cost p3) 10)
    (unused p4)
    (= (goal-size p4) 10)
    (= (glaze-cost p4) 15)
    (= (grind-cost p4) 30)
    (= (plane-cost p4) 20)
    (unused p5)
    (= (goal-size p5) 15)
    (= (glaze-cost p5) 20)
    (= (grind-cost p5) 45)
    (= (plane-cost p5) 30)
    (unused p6)
    (= (goal-size p6) 6)
    (= (glaze-cost p6) 11)
    (= (grind-cost p6) 18)
    (= (plane-cost p6) 12)
    (unused p7)
    (= (goal-size p7) 6)
    (= (glaze-cost p7) 11)
    (= (grind-cost p7) 18)
    (= (plane-cost p7) 12)
    (unused p8)
    (= (goal-size p8) 14)
    (= (glaze-cost p8) 19)
    (= (grind-cost p8) 42)
    (= (plane-cost p8) 28)
    (unused p9)
    (= (goal-size p9) 7)
    (= (glaze-cost p9) 12)
    (= (grind-cost p9) 21)
    (= (plane-cost p9) 14)
    (unused p10)
    (= (goal-size p10) 8)
    (= (glaze-cost p10) 13)
    (= (grind-cost p10) 24)
    (= (plane-cost p10) 16)
    (unused p11)
    (= (goal-size p11) 6)
    (= (glaze-cost p11) 11)
    (= (grind-cost p11) 18)
    (= (plane-cost p11) 12)
    (= (board-size b0) 44)
    (wood b0 teak)
    (surface-condition b0 rough)
    (available b0)
    (= (board-size b1) 40)
    (wood b1 teak)
    (surface-condition b1 smooth)
    (available b1)
    (= (board-size b2) 27)
    (wood b2 teak)
    (surface-condition b2 rough)
    (available b2)
    (= (board-size b3) 38)
    (wood b3 pine)
    (surface-condition b3 rough)
    (available b3)
    (= (board-size b4) 25)
    (wood b4 pine)
    (surface-condition b4 rough)
    (available b4)
    (= (board-size b5) 36)
    (wood b5 pine)
    (surface-condition b5 rough)
    (available b5)
    (= (board-size b6) 34)
    (wood b6 walnut)
    (surface-condition b6 smooth)
    (available b6)
    (= (board-size b7) 34)
    (wood b7 walnut)
    (surface-condition b7 rough)
    (available b7)
  )
  (:goal
    (and
      (preference g_p0_0 (and
          (colour p0 red)
          (wood p0 pine)
          (surface-condition p0 verysmooth)
          (treatment p0 varnished)
          (available p0)
      ))
      (preference g_p0_1 (and
          (wood p0 pine)
          (surface-condition p0 smooth)
          (available p0)
      ))
      (preference g_p0_2 (and
          (colour p0 red)
          (wood p0 walnut)
          (surface-condition p0 verysmooth)
          (treatment p0 glazed)
          (available p0)
      ))
      (preference g_p1_0 (and
          (colour p1 green)
          (wood p1 pine)
          (surface-condition p1 verysmooth)
          (available p1)
      ))
      (preference g_p1_1 (and
          (colour p1 white)
          (wood p1 pine)
          (surface-condition p1 verysmooth)
          (treatment p1 varnished)
          (available p1)
      ))
      (preference g_p1_2 (and
          (colour p1 mauve)
          (surface-condition p1 smooth)
          (treatment p1 glazed)
          (available p1)
      ))
      (preference g_p1_3 (and
          (wood p1 teak)
          (surface-condition p1 verysmooth)
          (treatment p1 glazed)
          (available p1)
      ))
      (preference g_p2_0 (and
          (colour p2 green)
          (wood p2 pine)
          (surface-condition p2 smooth)
          (available p2)
      ))
      (preference g_p2_1 (and
          (colour p2 black)
          (wood p2 walnut)
          (surface-condition p2 smooth)
          (treatment p2 glazed)
          (available p2)
      ))
      (preference g_p2_2 (and
          (colour p2 white)
          (wood p2 teak)
          (available p2)
      ))
      (preference g_p2_3 (and
          (wood p2 walnut)
          (surface-condition p2 smooth)
          (treatment p2 varnished)
          (available p2)
      ))
      (preference g_p3_0 (and
          (wood p3 pine)
          (surface-condition p3 smooth)
          (available p3)
      ))
      (preference g_p3_1 (and
          (colour p3 blue)
          (surface-condition p3 verysmooth)
          (available p3)
      ))
      (preference g_p3_2 (and
          (colour p3 white)
          (treatment p3 glazed)
          (available p3)
      ))
      (preference g_p3_3 (and
          (colour p3 red)
          (surface-condition p3 verysmooth)
          (treatment p3 varnished)
          (available p3)
      ))
      (preference g_p4_0 (and
          (colour p4 black)
          (wood p4 walnut)
          (surface-condition p4 smooth)
          (treatment p4 varnished)
          (available p4)
      ))
      (preference g_p4_1 (and
          (wood p4 teak)
          (treatment p4 varnished)
          (available p4)
      ))
      (preference g_p5_0 (and
          (colour p5 blue)
          (wood p5 walnut)
          (surface-condition p5 verysmooth)
          (treatment p5 glazed)
          (available p5)
      ))
      (preference g_p5_1 (and
          (colour p5 blue)
          (wood p5 teak)
          (surface-condition p5 smooth)
          (treatment p5 varnished)
          (available p5)
      ))
      (preference g_p6_0 (and
          (colour p6 mauve)
          (wood p6 teak)
          (surface-condition p6 verysmooth)
          (treatment p6 glazed)
          (available p6)
      ))
      (preference g_p6_1 (and
          (colour p6 blue)
          (wood p6 walnut)
          (surface-condition p6 verysmooth)
          (treatment p6 varnished)
          (available p6)
      ))
      (preference g_p6_2 (and
          (colour p6 black)
          (wood p6 pine)
          (surface-condition p6 verysmooth)
          (treatment p6 glazed)
          (available p6)
      ))
      (preference g_p7_0 (and
          (wood p7 teak)
          (surface-condition p7 smooth)
          (treatment p7 varnished)
          (available p7)
      ))
      (preference g_p7_1 (and
          (colour p7 green)
          (wood p7 pine)
          (surface-condition p7 verysmooth)
          (available p7)
      ))
      (preference g_p7_2 (and
          (colour p7 green)
          (wood p7 walnut)
          (surface-condition p7 verysmooth)
          (available p7)
      ))
      (preference g_p8_0 (and
          (colour p8 red)
          (wood p8 teak)
          (surface-condition p8 smooth)
          (treatment p8 glazed)
          (available p8)
      ))
      (preference g_p8_1 (and
          (colour p8 green)
          (wood p8 pine)
          (surface-condition p8 smooth)
          (treatment p8 varnished)
          (available p8)
      ))
      (preference g_p8_2 (and
          (colour p8 white)
          (wood p8 pine)
          (surface-condition p8 smooth)
          (treatment p8 varnished)
          (available p8)
      ))
      (preference g_p8_3 (and
          (colour p8 green)
          (wood p8 teak)
          (surface-condition p8 smooth)
          (treatment p8 glazed)
          (available p8)
      ))
      (preference g_p9_0 (and
          (colour p9 mauve)
          (wood p9 teak)
          (surface-condition p9 verysmooth)
          (available p9)
      ))
      (preference g_p9_1 (and
          (colour p9 red)
          (wood p9 walnut)
          (surface-condition p9 verysmooth)
          (treatment p9 varnished)
          (available p9)
      ))
      (preference g_p9_2 (and
          (colour p9 black)
          (surface-condition p9 verysmooth)
          (treatment p9 glazed)
          (available p9)
      ))
      (preference g_p10_0 (and
          (colour p10 black)
          (wood p10 pine)
          (surface-condition p10 smooth)
          (treatment p10 glazed)
          (available p10)
      ))
      (preference g_p10_1 (and
          (colour p10 white)
          (wood p10 teak)
          (surface-condition p10 smooth)
          (treatment p10 varnished)
          (available p10)
      ))
      (preference g_p11_0 (and
          (colour p11 blue)
          (surface-condition p11 smooth)
          (available p11)
      ))
      (preference g_p11_1 (and
          (colour p11 natural)
          (treatment p11 glazed)
          (available p11)
      ))
      (preference g_p11_2 (and
          (colour p11 red)
          (wood p11 teak)
          (surface-condition p11 smooth)
          (treatment p11 glazed)
          (available p11)
      ))
      (preference g_p11_3 (and
          (colour p11 mauve)
          (wood p11 teak)
          (available p11)
      ))
    )
  )
  (:metric maximize
    (- 3239
      (+ (total-cost)
         (* (is-violated g_p0_0) 91)
         (* (is-violated g_p0_1) 69)
         (* (is-violated g_p0_2) 88)
         (* (is-violated g_p1_0) 105)
         (* (is-violated g_p1_1) 91)
         (* (is-violated g_p1_2) 102)
         (* (is-violated g_p1_3) 116)
         (* (is-violated g_p2_0) 85)
         (* (is-violated g_p2_1) 93)
         (* (is-violated g_p2_2) 58)
         (* (is-violated g_p2_3) 83)
         (* (is-violated g_p3_0) 54)
         (* (is-violated g_p3_1) 72)
         (* (is-violated g_p3_2) 43)
         (* (is-violated g_p3_3) 73)
         (* (is-violated g_p4_0) 88)
         (* (is-violated g_p4_1) 58)
         (* (is-violated g_p5_0) 133)
         (* (is-violated g_p5_1) 113)
         (* (is-violated g_p6_0) 72)
         (* (is-violated g_p6_1) 81)
         (* (is-violated g_p6_2) 85)
         (* (is-violated g_p7_0) 80)
         (* (is-violated g_p7_1) 83)
         (* (is-violated g_p7_2) 76)
         (* (is-violated g_p8_0) 129)
         (* (is-violated g_p8_1) 104)
         (* (is-violated g_p8_2) 121)
         (* (is-violated g_p8_3) 136)
         (* (is-violated g_p9_0) 91)
         (* (is-violated g_p9_1) 83)
         (* (is-violated g_p9_2) 77)
         (* (is-violated g_p10_0) 95)
         (* (is-violated g_p10_1) 75)
         (* (is-violated g_p11_0) 63)
         (* (is-violated g_p11_1) 42)
         (* (is-violated g_p11_2) 76)
         (* (is-violated g_p11_3) 55)
  )))
)
