; woodworking 'not everything worthwhile' task with 12 parts
; Machines:
;   1 grinder
;   1 glazer
;   1 immersion-varnisher
;   1 planer
;   1 highspeed-saw
;   1 spray-varnisher
;   1 saw
; random seed: 3286

(define (problem wood-prob)
  (:domain woodworking)
  (:objects
    grinder0 - grinder
    glazer0 - glazer
    immersion-varnisher0 - immersion-varnisher
    planer0 - planer
    highspeed-saw0 - highspeed-saw
    spray-varnisher0 - spray-varnisher
    saw0 - saw
    green white blue mauve black red - acolour
    oak walnut pine - awood
    p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11 - part
    b0 b1 b2 b3 b4 - board
  )
  (:init
    (grind-treatment-change varnished colourfragments)
    (grind-treatment-change glazed untreated)
    (grind-treatment-change untreated untreated)
    (grind-treatment-change colourfragments untreated)
    (is-smooth smooth)
    (is-smooth verysmooth)
    (= (total-cost) 0)
    (has-colour glazer0 blue)
    (has-colour glazer0 mauve)
    (has-colour glazer0 white)
    (has-colour glazer0 black)
    (has-colour glazer0 red)
    (has-colour immersion-varnisher0 blue)
    (has-colour immersion-varnisher0 mauve)
    (has-colour immersion-varnisher0 white)
    (has-colour immersion-varnisher0 natural)
    (empty highspeed-saw0)
    (has-colour spray-varnisher0 blue)
    (has-colour spray-varnisher0 mauve)
    (has-colour spray-varnisher0 white)
    (has-colour spray-varnisher0 natural)
    (unused p0)
    (= (goal-size p0) 10)
    (= (glaze-cost p0) 15)
    (= (grind-cost p0) 30)
    (= (plane-cost p0) 20)
    (unused p1)
    (= (goal-size p1) 8)
    (= (glaze-cost p1) 13)
    (= (grind-cost p1) 24)
    (= (plane-cost p1) 16)
    (unused p2)
    (= (goal-size p2) 6)
    (= (glaze-cost p2) 11)
    (= (grind-cost p2) 18)
    (= (plane-cost p2) 12)
    (unused p3)
    (= (goal-size p3) 8)
    (= (glaze-cost p3) 13)
    (= (grind-cost p3) 24)
    (= (plane-cost p3) 16)
    (unused p4)
    (= (goal-size p4) 6)
    (= (glaze-cost p4) 11)
    (= (grind-cost p4) 18)
    (= (plane-cost p4) 12)
    (unused p5)
    (= (goal-size p5) 10)
    (= (glaze-cost p5) 15)
    (= (grind-cost p5) 30)
    (= (plane-cost p5) 20)
    (unused p6)
    (= (goal-size p6) 11)
    (= (glaze-cost p6) 16)
    (= (grind-cost p6) 33)
    (= (plane-cost p6) 22)
    (unused p7)
    (= (goal-size p7) 10)
    (= (glaze-cost p7) 15)
    (= (grind-cost p7) 30)
    (= (plane-cost p7) 20)
    (unused p8)
    (= (goal-size p8) 8)
    (= (glaze-cost p8) 13)
    (= (grind-cost p8) 24)
    (= (plane-cost p8) 16)
    (unused p9)
    (= (goal-size p9) 6)
    (= (glaze-cost p9) 11)
    (= (grind-cost p9) 18)
    (= (plane-cost p9) 12)
    (unused p10)
    (= (goal-size p10) 14)
    (= (glaze-cost p10) 19)
    (= (grind-cost p10) 42)
    (= (plane-cost p10) 28)
    (unused p11)
    (= (goal-size p11) 7)
    (= (glaze-cost p11) 12)
    (= (grind-cost p11) 21)
    (= (plane-cost p11) 14)
    (= (board-size b0) 17)
    (wood b0 oak)
    (surface-condition b0 rough)
    (available b0)
    (= (board-size b1) 36)
    (wood b1 pine)
    (surface-condition b1 rough)
    (available b1)
    (= (board-size b2) 7)
    (wood b2 pine)
    (surface-condition b2 rough)
    (available b2)
    (= (board-size b3) 36)
    (wood b3 walnut)
    (surface-condition b3 rough)
    (available b3)
    (= (board-size b4) 8)
    (wood b4 walnut)
    (surface-condition b4 rough)
    (available b4)
  )
  (:goal
    (and
      (preference g_p0_0 (and
          (wood p0 walnut)
          (surface-condition p0 verysmooth)
          (treatment p0 varnished)
          (available p0)
      ))
      (preference g_p1_0 (and
          (colour p1 blue)
          (surface-condition p1 verysmooth)
          (available p1)
      ))
      (preference g_p2_0 (and
          (colour p2 red)
          (wood p2 walnut)
          (surface-condition p2 verysmooth)
          (treatment p2 glazed)
          (available p2)
      ))
      (preference g_p3_0 (and
          (colour p3 mauve)
          (wood p3 pine)
          (surface-condition p3 verysmooth)
          (treatment p3 varnished)
          (available p3)
      ))
      (preference g_p4_0 (and
          (colour p4 white)
          (surface-condition p4 verysmooth)
          (available p4)
      ))
      (preference g_p5_0 (and
          (wood p5 walnut)
          (surface-condition p5 verysmooth)
          (treatment p5 varnished)
          (available p5)
      ))
      (preference g_p6_0 (and
          (colour p6 black)
          (wood p6 oak)
          (surface-condition p6 smooth)
          (treatment p6 glazed)
          (available p6)
      ))
      (preference g_p7_0 (and
          (colour p7 white)
          (wood p7 walnut)
          (surface-condition p7 verysmooth)
          (treatment p7 glazed)
          (available p7)
      ))
      (preference g_p8_0 (and
          (colour p8 natural)
          (wood p8 walnut)
          (surface-condition p8 verysmooth)
          (treatment p8 varnished)
          (available p8)
      ))
      (preference g_p9_0 (and
          (colour p9 blue)
          (treatment p9 varnished)
          (available p9)
      ))
      (preference g_p10_0 (and
          (colour p10 mauve)
          (wood p10 pine)
          (available p10)
      ))
      (preference g_p11_0 (and
          (wood p11 pine)
          (treatment p11 glazed)
          (available p11)
      ))
    )
  )
  (:metric maximize
    (- 750
      (+ (total-cost)
         (* (is-violated g_p0_0) 57)
         (* (is-violated g_p1_0) 57)
         (* (is-violated g_p2_0) 70)
         (* (is-violated g_p3_0) 76)
         (* (is-violated g_p4_0) 51)
         (* (is-violated g_p5_0) 86)
         (* (is-violated g_p6_0) 87)
         (* (is-violated g_p7_0) 95)
         (* (is-violated g_p8_0) 53)
         (* (is-violated g_p9_0) 42)
         (* (is-violated g_p10_0) 39)
         (* (is-violated g_p11_0) 37)
  )))
)
