clone_folder: c:\lgt3git
shallow_clone: true

branches:
  only:
    - master

install:
  # Add Inno Setup to PATH so the ISCC command is found
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

build_script:
  - iscc c:\lgt3git\scripts\windows\logtalk.iss /DPWD=%CD% /OOutput /F"logtalk-installer"

after_build:
  - cd Output
  - copy /y logtalk-installer.exe logtalk-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.exe
  - appveyor PushArtifact logtalk-%APPVEYOR_REPO_COMMIT_TIMESTAMP%.exe
