# Build PDF & ePub
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

formats:
  - epub
  - pdf

python:
  install:
    - requirements: manuals/sources/requirements.txt

sphinx:
  configuration: manuals/sources/conf.py
