#!/bin/sh

#############################################################################
## 
##   Logtalk Debian package auxiliary script
##   Last updated on December 27, 2019
## 
##   This file is part of Logtalk <https://logtalk.org/>  
##   Copyright 1998-2021 Paulo Moura <pmoura@logtalk.org>
##   
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##   
##       http://www.apache.org/licenses/LICENSE-2.0
##   
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
## 
#############################################################################

echo "Removing menu entries for some of the Logtalk integration scripts..."

if [ -x /usr/bin/update-menus ] ; then
	update-menus
fi

echo "Removing default definitions for the Logtalk environment variables..."

rm -f /etc/profile.d/logtalk.sh 2> /dev/null
rm -f /etc/profile.d/logtalk.csh 2> /dev/null

echo ""
echo "You have successfully uninstalled Logtalk!"
echo ""
