#!/bin/sh

#############################################################################
## 
##   Logtalk Debian package auxiliary script
## 
##   This file is part of Logtalk <http://logtalk.org/>  
##   Copyright 1998-2016 Paulo Moura <pmoura@logtalk.org>
##   
##   Licensed under the Apache License, Version 2.0 (the "License");
##   you may not use this file except in compliance with the License.
##   You may obtain a copy of the License at
##   
##       http://www.apache.org/licenses/LICENSE-2.0
##   
##   Unless required by applicable law or agreed to in writing, software
##   distributed under the License is distributed on an "AS IS" BASIS,
##   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##   See the License for the specific language governing permissions and
##   limitations under the License.
## 
#############################################################################

echo ""
echo "Uninstalling and de-registering Logtalk online documentation..."

if [ "$1" = "remove" ] || [ "$1" = "upgrade" ] ; then
	if which install-docs > /dev/null 2>&1 ; then
		install-docs -r logtalk-docs
	fi
fi

echo ""
echo "Removing Logtalk integration and documentation scripts..."

rm -rf /usr/share/logtalk/bin
