# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
def setup(app):
    app.add_css_file('css/custom.css')

# -- Project information -----------------------------------------------------

project = 'Logtalk APIs'
copyright = '1998-2026, Paulo Moura'
author = 'Paulo Moura'

# The short X.Y version
version = '3.103.0'
# The full version, including alpha/beta/rc tags
release = u'v3.103.0'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.intersphinx',
    'sphinxcontrib.spelling'
]

intersphinx_mapping = {'handbook': ('../handbook/','../../handbook/objects.inv')}

spelling_word_list_filename = '../../handbook/sources/spelling_wordlist.txt'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {'.rst': 'restructuredtext'}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'friendly'

highlight_language = 'logtalk'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_title = 'Logtalk ' + version
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'navigation_depth': 3
}
html_logo = 'logtalk.gif'
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_extra_path = ['android-chrome-192x192.png', 'android-chrome-512x512.png', 'apple-touch-icon.png', 'browserconfig.xml', 'favicon-16x16.png', 'favicon-32x32.png', 'favicon.ico', 'mstile-150x150.png', 'safari-pinned-tab.svg', 'site.webmanifest']

# html_last_updated_fmt = ''

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'logtalkapis'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    'pointsize': '10pt',
    'passoptionstopackages': r'''
        \PassOptionsToPackage{bookmarksdepth=0}{hyperref}
    ''',
    'preamble': r'''
        \definecolor{LogtalkRed}{HTML}{8C1D18}
        \definecolor{LogtalkBlue}{HTML}{245B78}
        \definecolor{LogtalkCode}{HTML}{F3F5F7}
        \definecolor{LogtalkCodeBorder}{HTML}{CCD3D8}
        \let\sphinxcodeold\sphinxcode
        \protected\def\sphinxcode#1{\textcolor{LogtalkRed}{\sphinxcodeold{#1}}}
        \setlength{\parskip}{2pt plus 1pt minus 1pt}
    ''',
    'sphinxsetup': r'''
        hmargin={1.8cm,1.8cm},
        vmargin={2cm,2cm},
        marginpar=1.2cm,
        TitleColor={HTML}{8C1D18},
        InnerLinkColor={HTML}{245B78},
        OuterLinkColor={HTML}{245B78},
        VerbatimColor={HTML}{F3F5F7},
        VerbatimBorderColor={HTML}{CCD3D8},
        verbatimwithframe=true,
        verbatimwrapslines=true,
        verbatimforcewraps=true,
        verbatimmaxunderfull=2
    ''',
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'LogtalkAPIs-' + version + '.tex', u'Logtalk APIs',
     u'Paulo Moura', 'manual'),
]
latex_engine = 'xelatex'
latex_use_xindy = False


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'library', 'Logtalk APIs',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'LogtalkAPIs-' + version, 'Logtalk APIs',
     u'Paulo Moura', 'Logtalk APIs', 'Logtalk programming APIs.',
     'Programming Languages'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project + '\n\n' + release
epub_author = author
epub_publisher = author
epub_copyright = copyright

epub_basename = 'LogtalkAPIs-' + version
# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']
