.TH bplgt 1 "January 3, 2015" "Logtalk 3.00.0" "Logtalk Documentation"

.SH NAME
bplgt \- Logtalk integration script for B-Prolog

.SH SYNOPSIS
.B bplgt
[
.B \-g
.I goal
]

.SH DESCRIPTION
\fBbplgt\fR is a Logtalk integration script for B-Prolog. It automatically loads the B-Prolog adapter file, the Logtalk compiler and runtime, the Logtalk default table of library names and paths, and any existing settings file found on the startup directory or in the Logtalk user directory.

.SH OPTIONS
.TP
.BI \-g \ goal
Initialization goal, written between double quotes, to be executed after Logtalk startup.

.SH REQUIREMENTS
B-Prolog 7.8 or a later version is required. This integration script looks for a "bp" executable in the system path.

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user directory.

.SH FILES
.TP
.BI $LOGTALKHOME/integration/logtalk_bp.pl
Prolog file used for loading the necessary files for starting Logtalk using B-Prolog as the back-end compiler.
.TP
.BI $LOGTALKHOME/adapters/b.pl
The B-Prolog adapter file.
.TP
.BI $LOGTALKHOME/core/core.pl
The Logtalk core compiler and runtime file.
.TP
.BI $LOGTALKHOME/paths/paths.pl
The default table of library names and paths.
.TP
.BI ./settings.lgt
Logtalk settings file (for overriding default settings in the adapter files). May not exist.
.TP
.BI $LOGTALKUSER/settings.lgt
Logtalk settings file (for overriding default settings in the adapter files). May not exist.

.SH "SEE ALSO"
The Logtalk website at <http://logtalk.org/>
.PP
The Logtalk User and Reference Manuals at \fB$LOGTALKHOME/manuals/index.html\fR
.PP
The B-Prolog website at <http://www.probp.com/>
.PP
logtalk_user_setup(1),\ logtalk_version_select(1),\ logtalk_backend_select(1)

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2015 Paulo Moura.
