.TH jiplgt 1 "May 2, 2015" "Logtalk 3.00.1" "Logtalk Documentation"

.SH NAME
jiplgt \- Logtalk integration script for JIProlog

.SH SYNOPSIS
.B jiplgt
[
.B \-g
.I goal
]

.SH DESCRIPTION
\f3jiplgt\f1 is a Logtalk integration script for JIProlog. It automatically loads the JIProlog adapter file, the Logtalk compiler and runtime, the Logtalk default table of library names and paths, and any existing settings file found on the startup directory or in the Logtalk user directory.

.SH OPTIONS
.TP
.I goal
Initialization goal, written between double quotes, to be executed after Logtalk startup.

.SH REQUIREMENTS
JIProlog 4.0.13 or a later version is required. This integration script looks for a \f3jipconsole.jar\f1 file in the \f3$JIP_HOME\f1 directory.

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user directory.
.TP
.B JIP_HOME
Specifies the location of the JIProlog installation directory.

.SH FILES
.TP
.BI $LOGTALKHOME/integration/logtalk_ji.pl
Prolog file used for loading the necessary files for starting Logtalk using JIProlog as the back-end compiler.
.TP
.BI $LOGTALKHOME/adapters/ji.pl
The JIProlog adapter file.
.TP
.BI $LOGTALKHOME/core/core.pl
The Logtalk core compiler and runtime file.
.TP
.BI $LOGTALKHOME/paths/paths.pl
The default table of library names and paths.
.TP
.BI ./settings.lgt
Logtalk settings file (for overriding default settings in the adapter files). May not exist.
.TP
.BI $LOGTALKUSER/settings.lgt
Logtalk settings file (for overriding default settings in the adapter files). May not exist.

.SH CAVEATS
The first run of this script may require using "sudo" depending on the writing permissions of the Logtalk installation directory.

.SH "SEE ALSO"
The Logtalk website at <http://logtalk.org/>
.PP
The Logtalk User and Reference Manuals at \f2$LOGTALKHOME/manuals/index.html\f1
.PP
The JIProlog website at <http://www.jiprolog.com/>
.PP
logtalk_user_setup(1),\ logtalk_version_select(1),\ logtalk_backend_select(1)

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2015 Paulo Moura.
