.TH lgt2rst 1 "October 4, 2018" "Logtalk 3.21.0" "Logtalk Documentation"

.SH NAME
lgt2rst \- Logtalk script for converting XML documenting files into reStructuredText files

.SH SYNOPSIS
.B lgt2rst
[
.B \-d
.I directory
]
[
.B \-p
.I processor
]
.br
.B lgt2rst
.B \-h

.SH DESCRIPTION
\fBlgt2rst\fR is a Logtalk script for converting all Logtalk XML documenting files in the current directory into  reStructuredText files. Assumes UTF-8 encoding.

.SH OPTIONS
.TP
.B \-d
.I directory
Output directory for the reStructuredText files.
.TP
.B \-p
.I processor
XSLT processor.
.TP
.B \-h
Prints a summary of the script options.

.SH REQUIREMENTS
Requires a compatible XSLT processor. See the script help screen for more information.

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user directory.

.SH FILES
.TP
.BI $LOGTALKHOME/tools/lgtdoc/xml/logtalk_entity.dtd
The Logtalk entity DTD file.
.TP
.BI $LOGTALKHOME/tools/lgtdoc/xml/logtalk_index.dtd
The Logtalk index DTD file.
.TP
.BI $LOGTALKUSER/tools/lgtdoc/xml/custom.ent
The Logtalk custom entities file.
.TP
.BI $LOGTALKHOME/tools/lgtdoc/xml/logtalk_entity.xsd
The Logtalk entity XML Schema file.
.TP
.BI $LOGTALKHOME/tools/lgtdoc/xml/logtalk_index.xsd
The Logtalk index XML Schema file.
.TP
.BI $LOGTALKUSER/tools/lgtdoc/xml/lgtrst.xsl
The default XSLT file.

.SH "SEE ALSO"
The Logtalk website at <https://logtalk.org/>
.PP
The Logtalk User and Reference Manuals at \fB$LOGTALKHOME/manuals/index.html\fR
.PP
logtalk_user_setup(1),\ lgt2html(1),\ lgt2xml(1),\ lgt2pdf(1),\ lgt2md(1),\ lgt2txt(1)

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2018 Paulo Moura.
