.TH lgt2svg 1 "April 6, 2020" "Logtalk 3.38.0" "Logtalk Documentation"

.SH NAME
lgt2svg \- Logtalk script for converting DOT diagram files into SVG files

.SH SYNOPSIS
.B lgt2svg
.br
.B lgt2svg
.B \-v
.br
.B lgt2svg
.B \-h

.SH DESCRIPTION
\fBlgt2svg\fR is a Logtalk script for converting DOT diagram files into SVG files.

.SH REQUIREMENTS
Requires a recent version of Graphviz installed with the \fBdot\fR executable available from the system \fBPATH\fR.

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user directory.

.SH FILES
.TP
.BI $LOGTALKUSER/tools/diagrams/zoom.png
Zoom icon for SVG diagram nodes.
.TP
.BI $LOGTALKUSER/tools/diagrams/diagrams.css
CSS file styling the SVG diagram files.

.SH "SEE ALSO"
The Logtalk website at https://logtalk.org/
.PP
The Logtalk User and Reference Manuals at \fB$LOGTALKHOME/manuals/index.html\fR

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2020 Paulo Moura.
