.TH lgt2txt 1 "November 3, 2014" "Logtalk 3.00.0" "Logtalk Documentation"

.SH NAME
lgt2txt \- Logtalk script for converting XML documenting files into text files

.SH SYNOPSIS
.B lgt2txt
[
.B \-d
.I directory
]
[
.B \-p
.I processor
]
.br
.B lgt2txt
.B \-h

.SH DESCRIPTION
\fBlgt2txt\fR is a Logtalk script for converting all Logtalk XML documenting files in the current directory into text files. Assumes UTF-8 encoding.

.SH OPTIONS
.TP
.B \-d
.I directory
Output directory for the text files.
.TP
.B \-p
.I processor
XSLT processor.
.TP
.B \-h
Prints a summary of the script options.

.SH REQUIREMENTS
Requires a compatible XSLT processor. See the script help screen for more information.

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user directory.

.SH FILES
.TP
.BI $LOGTALKHOME/tools/lgtdoc/xml/logtalk.dtd
The Logtalk DTD file.
.TP
.BI $LOGTALKUSER/tools/lgtdoc/xml/custom.ent
The Logtalk custom entities file.
.TP
.BI $LOGTALKHOME/tools/lgtdoc/xml/logtalk.xsd
The Logtalk XML Schema file.
.TP
.BI $LOGTALKUSER/tools/lgtdoc/xml/lgttxt.xsl
The default XSLT file.

.SH "SEE ALSO"
The Logtalk website at <http://logtalk.org/>
.PP
The Logtalk User and Reference Manuals at \fB$LOGTALKHOME/manuals/index.html\fR
.PP
logtalk_user_setup(1),\ lgt2html(1),\ lgt2xml(1),\ lgt2pdf(1),\ lgt2md(1)

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2015 Paulo Moura.
