.TH lgtenv 1 "January 11, 2023" "Logtalk 3.62.0" "Logtalk Documentation"

.SH NAME
lgtenv \- Logtalk script for creating packs virtual environments

.SH SYNOPSIS
.B lgtenv -v
.br
.B lgtenv
[\fB-d \fIdirectory\fR]
[\fB-c\fR]
.br
.B lgtenv -h

.SH DESCRIPTION
\fBlgtenv\fR is a Logtalk script for creating packs virtual environments.

.SH OPTIONS
.TP
.BI \-d
Directory where to create the virtual environment. Default is the current directory.
.TP
.BI \-c
Create directory if it does not exist.

.SH REQUIREMENTS
Requires \fBdirenv\fR to be installed (see https://github.com/direnv/direnv).

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user directory.

.SH "SEE ALSO"
The Logtalk website at https://logtalk.org/
.PP
The Logtalk User and Reference Manuals at \fB$LOGTALKHOME/manuals/index.html\fR

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 2023 Paulo Moura.
