.TH logtalk_tester 1 "March 26, 2016" "Logtalk 3.04.2" "Logtalk Documentation"

.SH NAME
logtalk_tester \- Logtalk script for automating running unit tests

.SH SYNOPSIS
.B logtalk_tester -v
.br
.B logtalk_tester [-p 
.I prolog
.B ] [-m
.I mode
.B ] [-f
.I format
.B ] [-d
.I results
.B ] [-t
.I timeout
.B ] [--
.I arguments
.B ]
.br
.B logtalk_tester -h

.SH DESCRIPTION
\f3logtalk_tester\f1 is a script for automating running Logtalk unit tests. This script runs unit tests found on the current directory and recursively in its sub-directories by scanning for \f2tester.lgt\f1 and \f2tester.logtalk\f1 source files. In case of failed unit tests, timed out test sets, or crashed test sets, this script returns an exit code of \f21\f1.

.SH OPTIONS
.TP
.BI \-v
Print script version.
.TP
.BI \-p
Back-end Prolog compiler. Default is YAP. The following identifiers are used: B-Prolog - \f2b\f1, CxProlog - \f2cx\f1, ECLiPSe - \f2eclipse\f1, GNU Prolog - \f2gnu\f1, JIProlog - \f2ji\f1, Lean Prolog - \f2lean\f1, Qu-Prolog - \f2qp\f1, SICStus Prolog - \f2sicstus\f1, SWI-Prolog - \f2swi\f1, XSB - \f2xsb\f1, XSB-MT - \f2xsbmt\f1, YAP - \f2yap\f1.
.TP
.BI \-m
Compilation mode. Default is \f2normal\f1. Possible values are \f2normal\f1, \f2debug\f1, and \f2all\f1.
.TP
.BI \-f
Format for writing the test results. Default is \f2default\f1. Possible values are \f2default\f1, \f2tap\f1, and \f2xunit\f1.
.TP
.BI \-d
Directory to store the test results. Default is the local \f2./logtalk_tester_logs\f1 directory.
.TP
.BI \-t
Timeout in seconds for running each test set. Default is \f20\f1; i.e. disabled.
.TP
.BI \--
Arguments to be passed to the integration script used to run the tests (no default).
.TP
.BI \-h
Provide help on script usage.

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user directory.

.SH FILES
.TP
.BI $LOGTALKUSER/library/tester_versions.lgt
Logtalk source file used for printing the Logtalk and back-end Prolog compiler versions.

.SH "SEE ALSO"
The Logtalk website at <http://logtalk.org/>
.PP
The Logtalk User and Reference Manuals at \f2$LOGTALKHOME/manuals/index.html\f1

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2016 Paulo Moura.
