.TH logtalk_tester 1 "May 24, 2020" "Logtalk 3.39.0" "Logtalk Documentation"

.SH NAME
logtalk_tester \- Logtalk script for automating running unit tests

.SH SYNOPSIS
.B logtalk_tester -v
.br
.B logtalk_tester [-o
.I output
.B ] [-p 
.I prolog
.B ] [-m
.I mode
.B ] [-f
.I format
.B ] [-d
.I results
.B ] [-t
.I timeout
.B ] [-s
.I prefix
.B ] [-c
.I report
.B ] [-l
.I level
.B ] [-i
.I options
.B ] [-g
.I goal
.B ] [-r
.I seed
.B ] [--
.I arguments
.B ]
.br
.B logtalk_tester -h

.SH DESCRIPTION
\fBlogtalk_tester\fR is a script for automating running Logtalk unit tests. This script runs unit tests found on the current directory and recursively in its sub-directories by scanning for \fItester.lgt\fR and \fItester.logtalk\fR source files. The script returns a non-zero exit status in case of failed tests or test set errors. When a \fItester.sh\fR file exists in the current directory, the file is sourced before running the tests. The \fItester.sh\fR file is sourced with all the parameters passed to the \fIlogtalk_tester\fR script.

.SH OPTIONS
.TP
.BI \-v
Print script version.
.TP
.BI \-o
Output verbosity. Default is \fIverbose\fR. Valid values are \fIverbose\fR and \fIminimal\fR.
.TP
.BI \-p
Backend Prolog compiler. Default is SWI-Prolog. The following identifiers are used: B-Prolog - \fIb\fR, Ciao Prolog - \fIciao\fR, CxProlog - \fIcx\fR, ECLiPSe - \fIeclipse\fR, GNU Prolog - \fIgnu\fR, JIProlog - \fIji\fR, Lean Prolog - \fIlean\fR, Qu-Prolog - \fIqp\fR, SICStus Prolog - \fIsicstus\fR, SWI-Prolog - \fIswi\fR, SWI-Prolog with Logtalk pack - \fIswipack\fR, XSB - \fIxsb\fR, XSB-MT - \fIxsbmt\fR, YAP - \fIyap\fR.
.TP
.BI \-m
Compilation mode. Default is \fInormal\fR. Valid values are \fIoptimal\fR, \fInormal\fR, \fIdebug\fR, and \fIall\fR.
.TP
.BI \-f
Format for writing the test results. Default is \fIdefault\fR. Valid values are \fIdefault\fR, \fItap\fR, and \fIxunit\fR.
.TP
.BI \-d
Directory to store the test results. Default is the local \fI./logtalk_tester_logs\fR directory.
.TP
.BI \-t
Timeout in seconds for running each test set. Default is \fI0\fR; i.e. disabled.
.TP
.BI \-s
Path prefix to suppress when printing test suite and test result paths. Default is the user home directory.
.TP
.BI \-c
Code coverage report. Default is \fInone\fR. Valid values are \fIxml\fR and \fInone\fR.
.TP
.BI \-l
Directory depth level to look for test sets. Level 1 means current directory only. Default is to recurse into all sub-directories.
.TP
.BI \-i
Integration script command-line options (no default).
.TP
.BI \-g
Initialization goal. Default is true. Called after loading the Logtalk compiler and runtime.
.TP
.BI \-r
Random generator starting seed goal (no default).
.TP
.BI \--
Arguments to be passed to the tests (no default).
.TP
.B \-h
Provide help on script usage.

.SH "EXIT STATUS"
.TP
.B 0
All non-skipped tests pass and there are no broken, timed out, or crashed test sets.
.TP
.B 1
Some tests fail but there are no broken, timed out, or crashed test sets.
.TP
.B 3
One or more test sets timed out while executing but there are no broken or crashed test sets.
.TP
.B 5
One or more test sets are broken and thus could not be executed but there are no crashed test sets.
.TP
.B 7
One or more test sets crashed the process running them.
.TP
.B 9
The sourced \fItester.sh\fR file returned a non-zero code.

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user directory.

.SH FILES
.TP
.BI $LOGTALKUSER/library/tester_versions.lgt
Logtalk source file used for printing the Logtalk and backend Prolog compiler versions.
.TP
.BI $LOGTALKUSER/library/parallel_logtalk_processes_setup.pl
Logtalk source file used for parallel Logtalk processes with selected backend Prolog compilers.
.TP
.BI $LOGTALKUSER/tools/lgtunit/automation_report.lgt
Logtalk source file that intercepts unit test execution messages and generates report files that are parsed by this script.

.SH "SEE ALSO"
The Logtalk website at https://logtalk.org/
.PP
The Logtalk User and Reference Manuals at \fB$LOGTALKHOME/manuals/index.html\fR

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2020 Paulo Moura.
