.TH logtalk_user_setup 1 "May 27, 2012" "Logtalk 3.00.0" "Logtalk Documentation"

.SH NAME
logtalk_user_setup \-- Logtalk user setup script

.SH SYNOPSIS
.B logtalk_user_setup

.SH DESCRIPTION
\f3logtalk_user_setup\f1 is a Logtalk user setup script for copying the Logtalk user-modifiable files and directories to the location pointed by the environment variable LOGTALKUSER (defaults to "~/logtalk"). When the Logtalk user directory already exists, a backup is made to a directory whose name starts with "logtalk-backup-" and a new Logtalk user directory is created.

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user directory.

.SH "SEE ALSO"
The Logtalk website at http://logtalk.org/
.PP
The Logtalk User and Reference Manuals at $LOGTALKHOME/manuals/index.html
.PP
logtalk_version_select(1),\ logtalk_backend_select(1)

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2013 Paulo Moura.
