.TH logtalk_allure_report 1 "January 13, 2021" "Logtalk 3.44.0" "Logtalk Documentation"

.SH NAME
logtalk_allure_report \- Logtalk script for generating Allure reports

.SH SYNOPSIS
.B logtalk_allure_report -v
.br
.B logtalk_allure_report
[\fB-t \fItests\fR]
[\fB-i \fIresults\fR]
[\fB-o \fIreport\fR]
[\fB-p\fR]
.br
.B logtalk_allure_report -h

.SH DESCRIPTION
\fBlogtalk_allure_report\fR is a script for generating Allure reports. Requires running first the \fIlogtalk_tester\fR script using the \fI-f xunit\fR or \fI-f xunit_net_v2\fR command-line option.

.SH OPTIONS
.TP
.BI \-v
Print script version.
.TP
.BI \-t
The directory containing the tests (i.e. the directory where the \fIlogtalk_tester\fR script was run.
.TP
.BI \-i
Directory where to save the test results (i.e. the xUnit reports) for generating the report.
.TP
.BI \-o
Directory where the report is to be saved.
.TP
.BI \-p
Preprocess results but do not generate report. Useful when the actual generatation of the report is delegated to e.g. a Docker service or a Jenkins plug-in.
.TP
.B \-h
Provide help on script usage.

.SH "EXIT STATUS"
.TP
.B 0
Allure report successfully created.

.SH EXAMPLES
.TP
Run all tests on the current directory and sub-directories using the GNU Prolog backend, with results in the required xUnit format, generate and open an Allure report:
\fBlogtalk_tester -p gnu -f xunit\fR
.br
\fBlogtalk_allure_report\fR
.br
\fBallure open\fR

.SH IMPLEMENTATION NOTES
Tested using Allure 2.13.8.

.SH "SEE ALSO"
The Allure website at http://allure.qatools.ru
.PP
The Logtalk website at https://logtalk.org/
.PP
The Logtalk User and Reference Manuals at \fB$LOGTALKHOME/manuals/index.html\fR

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2021 Paulo Moura.
