.TH logtalk_version_select 1 "January 2, 2013" "Logtalk 3.00.0" "Logtalk Documentation"

.SH NAME
logtalk_version_select \-- Logtalk script for switching between installed Logtalk versions

.SH SYNOPSIS
.B logtalk_version_select -v
.br
.B logtalk_version_select -l
.br
.B logtalk_version_select -s
.br
.B logtalk_version_select 
.I version
.br
.B logtalk_version_select -h

.SH DESCRIPTION
\f3logtalk_version_select\f1 is a Logtalk script for switching between installed Logtalk versions. This script doesn't change the Logtalk user directory. This script is loosely based on the "python_select" script.

.SH OPTIONS
.TP
.BI \-v
Print script version.
.TP
.BI \-l
List available versions.
.TP
.BI \-s
Show the currently selected version.
.TP
.BI \-h
Provide help on script usage.

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user directory.

.SH "SEE ALSO"
The Logtalk website at http://logtalk.org/
.PP
The Logtalk User and Reference Manuals at $LOGTALKHOME/manuals/index.html
.PP
logtalk_user_setup(1),\ logtalk_backend_select(1)

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2014 Paulo Moura.
