.TH qplgt 1 "January 26, 2013" "Logtalk 3.00.0" "Logtalk Documentation"

.SH NAME
qplgt \-- Logtalk integration script for Qu-Prolog

.SH SYNOPSIS
.B qplgt
[
.B \-g
.I goal
]

.SH DESCRIPTION
\f3qplgt\f1 is a Logtalk integration script for Qu-Prolog. It automatically loads the Qu-Prolog adapter file, the Logtalk compiler and runtime, the Logtalk default table of library names and paths, and any existing settings file found on the startup directory or in the Logtalk user directory.

.SH OPTIONS
.TP
.BI \-g\ goal
Initialization goal, written between double quotes, to be executed after Logtalk startup.

.SH REQUIREMENTS
Qu-Prolog 9.0 or a later version is required.

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user directory.

.SH FILES
.TP
.BI $LOGTALKHOME/integration/logtalk_qp.pl
Prolog file used for loading the necessary files for starting Logtalk using Qu-Prolog as the back-end compiler.
.TP
.BI $LOGTALKHOME/adapters/qp.pl
The Qu-Prolog adapter file.
.TP
.BI $LOGTALKHOME/core/core.pl
The Logtalk core compiler and runtime file.
.TP
.BI $LOGTALKHOME/paths/paths.pl
The default table of library names and paths.
.TP
.BI ./settings.lgt
Logtalk settings file (for overriding default settings in the adapter files). May not exist.
.TP
.BI $LOGTALKUSER/settings.lgt
Logtalk settings file (for overriding default settings in the adapter files). May not exist.

.SH "SEE ALSO"
The Logtalk website at http://logtalk.org/
.PP
The Logtalk User and Reference Manuals at $LOGTALKHOME/manuals/index.html
.PP
The Qu-Prolog website at http://www.itee.uq.edu.au/~pjr/HomePages/QuPrologHome.html
.PP
logtalk_user_setup(1),\ logtalk_version_select(1),\ logtalk_backend_select(1)

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2013 Paulo Moura.
