.TH sicstuslgt 1 "January 2, 2013" "Logtalk 3.00.0" "Logtalk Documentation"

.SH NAME
sicstuslgt \-- Logtalk integration script for SICStus Prolog

.SH SYNOPSIS
.B sicstuslgt
[
.B \--goal
.I goal
]

.SH DESCRIPTION
\f3sicstuslgt\f1 is a Logtalk integration script for SICStus Prolog. It automatically loads the SICStus Prolog adapter file, the Logtalk compiler and runtime, the Logtalk default table of library names and paths, and any existing settings file found on the startup directory or in the Logtalk user directory.

.SH OPTIONS
.TP
.BI \--goal\ goal
Initialization goal, written between double quotes, to be executed after Logtalk startup.

.SH REQUIREMENTS
SICStus-Prolog 4.1.0 (or later versions) is required.

.SH ENVIRONMENT
.TP
.B LOGTALKHOME
Specifies the location of the Logtalk installation.
.TP
.B LOGTALKUSER
Specifies the location of the Logtalk user directory.

.SH FILES
.TP
.BI $LOGTALKHOME/integration/logtalk_sicstus.pl
Prolog file used for loading the necessary files for starting Logtalk using SICStus Prolog as the back-end compiler.
.TP
.BI $LOGTALKHOME/adapters/sicstus.pl
The SICStus Prolog adapter file.
.TP
.BI $LOGTALKHOME/core/core.pl
The Logtalk core compiler and runtime file.
.TP
.BI $LOGTALKHOME/paths/paths.pl
The default table of library names and paths.
.TP
.BI ./settings.lgt
Logtalk settings file (for overriding default settings in the adapter files). May not exist.
.TP
.BI $LOGTALKUSER/settings.lgt
Logtalk settings file (for overriding default settings in the adapter files). May not exist.

.SH "SEE ALSO"
The Logtalk website at http://logtalk.org/
.PP
The Logtalk User and Reference Manuals at $LOGTALKHOME/manuals/index.html
.PP
The SICStus Prolog website at http://www.sics.se/isl/sicstus.html
.PP
logtalk_user_setup(1),\ logtalk_version_select(1),\ logtalk_backend_select(1)

.SH AUTHOR
Paulo Moura <pmoura@logtalk.org>

.SH COPYRIGHT
Copyright (c) 1998-2014 Paulo Moura.
